#!/usr/bin/env python3
"""Render parity policy snippets in developer docs from machine-readable policy JSON."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
POLICY_PATH = ROOT / "docs" / "toolchain_parity_policy.json"
START = "<!-- PARITY_POLICY:START -->"
END = "<!-- PARITY_POLICY:END -->"


def _render_block(policy: dict[str, object]) -> str:
    python_version = str(policy["python_version"])
    tier1 = list(policy["mypy"]["tier1_scope"])
    tier2 = list(policy["mypy"]["tier2_scope"])
    make_targets = list(policy["canonical_make_targets"])
    hook_args = ["--config-file=pyproject.toml", *tier1]
    lines = [
        START,
        "<!-- Generated by .github/scripts/render_toolchain_parity_docs.py; do not edit by hand. -->",
        f"- Python baseline: `{python_version}`",
        f"- Tier 1 mypy scope: `{tier1}`",
        f"- Tier 1 mypy hook args: `{hook_args}`",
        f"- Tier 2 mypy scope: `{tier2}`",
        "- Canonical Make targets:",
        *[f"  - `{target}`" for target in make_targets],
        END,
    ]
    return "\n".join(lines)


def _replace_block(text: str, block: str) -> str:
    start = text.find(START)
    end = text.find(END)
    if start == -1 or end == -1 or end < start:
        raise RuntimeError("Missing PARITY_POLICY markers in doc.")
    end += len(END)
    return text[:start] + block + text[end:]


def main() -> int:
    policy = json.loads(POLICY_PATH.read_text(encoding="utf-8"))
    block = _render_block(policy)
    for doc_path in [ROOT / "docs" / "dev_toolchain_parity.md", ROOT / "docs" / "DEVELOPMENT.md"]:
        updated = _replace_block(doc_path.read_text(encoding="utf-8"), block)
        doc_path.write_text(updated + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
